### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [9]:
import random
import numpy as np

vector = np.random.rand(10)
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])

print("Вектор: \n", vector, "\nРозмір вектора: ", vector.shape)
print("Матриця: \n", matrix, "\nРозмір матриці: ", matrix.shape)

Вектор: 
 [0.25096181 0.02615459 0.1288002  0.87884236 0.22362909 0.47430952
 0.93250145 0.39927717 0.22936572 0.15766098] 
Розмір вектора:  (10,)
Матриця: 
 [[11 14 17]
 [20 23 26]
 [29 32 35]] 
Розмір матриці:  (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [17]:
# 1. Додайте до кожного значення вектора vector число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
print(np.round(vector + 10, 2), '\n')

# 2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
print(matrix * 2, '\n')

# 3. Створіть новий вектор, який містить квадрат кожного vector без циклів.
vector_1 = vector ** 2
vector_2 = np.round(vector + 10, 2) ** 2

print(vector_1, '\n')
print(vector_2)

[10.25 10.03 10.13 10.88 10.22 10.47 10.93 10.4  10.23 10.16] 

[[22 28 34]
 [40 46 52]
 [58 64 70]] 

[6.29818292e-02 6.84062481e-04 1.65894918e-02 7.72363899e-01
 5.00099715e-02 2.24969524e-01 8.69558962e-01 1.59422260e-01
 5.26086319e-02 2.48569862e-02] 

[105.0625 100.6009 102.6169 118.3744 104.4484 109.6209 119.4649 108.16
 104.6529 103.2256]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [18]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [29]:
# 1. Задані дві матриці A і Bрозмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю result_matrix на екран
result_matrix = np.dot(B, A)
print(result_matrix, '\n')

# 2. Заданий вектор C розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите result_matrix на вектор C і який результат буде. А потім виконайте множення і виведіть результат на екран.
# отримаю розмірність 2х1, оскільки result_matrix: 2x2 множиться на C: 2x1
print(np.dot(result_matrix, C), '\n')

# 3. Задана матриця D розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите result_matrix на матрицю D і який результат буде. А потім виконайте множення і виведіть результат на екран.
# отримаю розмірність 2х2, оскільки result_matrix: 2x2 множиться на D: 2x2

print(np.dot(result_matrix, D))

[[0.7281 0.5202]
 [0.2034 0.2846]] 

[[0.5202]
 [0.2846]] 

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [58]:
# 1. Транспонуйте result_matrix.
print(result_matrix.T, '\n')

# 2. Зробіть транспонування вектора vector і виведіть форму нової структури. Чи бачите ви зміну?
# не побачив зміни з не транспонованим вектором, такий спосіб транспонування можна використати у випадку якщо зробити vector.reshape(-1, 1), тоді зміна буде присутня
print(vector.T, '\n')

# 3. Використайте операцію numpy.expand_dims над вектором vector з аргументом axis=1. Запишіть отриманий результат в змінну column_vector і виведіть на екран. Порівняйте з vector.
# в даному випадку ми збільшили розмірність вектору, його розмір становить (10, 1), кожне число є масивом з єдиним елементом, тобто маємо масив з 10 масивів з 1 числом
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)
print(column_vector.shape, '\n')

# 4. Зробіть транспонування column_vector, виведіть результат на екран разом з розмірностями отриманої структури.
# транспонування перетворило наші 10 масивів в 1 масив з масивом 10 чисел
print(column_vector.T)
print(column_vector.T.shape)

[[0.7281 0.2034]
 [0.5202 0.2846]] 

[0.25096181 0.02615459 0.1288002  0.87884236 0.22362909 0.47430952
 0.93250145 0.39927717 0.22936572 0.15766098] 

[[0.25096181]
 [0.02615459]
 [0.1288002 ]
 [0.87884236]
 [0.22362909]
 [0.47430952]
 [0.93250145]
 [0.39927717]
 [0.22936572]
 [0.15766098]]
(10, 1) 

[[0.25096181 0.02615459 0.1288002  0.87884236 0.22362909 0.47430952
  0.93250145 0.39927717 0.22936572 0.15766098]]
(1, 10)
